#!/usr/bin/env python3.11
"""
cleanup_rekordbox_db.py
=======================
Synchronises ~/Library/Pioneer/rekordbox/master.db with a Rekordbox XML file
generated by traktor_to_rekordbox.py.

What it does:
  1. Backs up master.db
  2. Removes old/duplicate import folder trees, keeping only the canonical
     "01 - Styles / 02 - DJ / …" tree produced by the most recent run of
     traktor_to_rekordbox.py
  3. Adds any playlists present in the XML but missing from the DB
     (creates parent folders as needed)
  4. Adds any user tracks present in the XML but missing from the DB
     (inserts djmdContent + djmdCue rows and links them to their playlists)

Usage:
  python3.11 cleanup_rekordbox_db.py [--xml PATH] [--dry-run]

Defaults:
  --xml   ~/projects/rekordbox-tools/traktor_to_rekordbox.xml
"""

import argparse
import datetime
import os
import shutil
import uuid
import zlib
from pathlib import Path
from urllib.parse import unquote

import sqlcipher3 as sqlite3
import xml.etree.ElementTree as ET

# ── Constants ────────────────────────────────────────────────────────────────
DB_PATH  = Path.home() / "Library/Pioneer/rekordbox/master.db"
XML_PATH = Path.home() / "projects/rekordbox-tools/traktor_to_rekordbox.xml"
KEY = "402fd482c38817c35ffa8ffb8c7d93143b749e7d315df7a81732a1ff43608497"

# Root folder names that belong to the canonical (current) tree.
# Any other root folders with duplicate names are removed.
CANONICAL_ROOT_FOLDERS = {
    "01 - Styles", "02 - DJ", "03 - Events", "04 - History",
    "05 - Dated",  "06 - Prep", "07 - Albums", "Other",
}

# Root-level items (by name) that should never be touched
PROTECTED_ROOT_NAMES = {
    "All tagged", "0 - Huge Tracks", "My tracks",
    "Power Mixes - Prog", "Power Mixes - Techno",
    "Preparation", "Tracks to Produce", "_LOOPS", "_RECORDINGS",
    "temp tracks check", "All tracks modified at or after 2024/8/4",
    "HISTORY 2023-08-19", "HISTORY 2025-04-01", "Jam Rob HISTORY 2024-08-18 (1)",
}

FILE_TYPE = {".mp3":1, ".m4a":6, ".aac":6, ".aif":10, ".aiff":10,
             ".wav":11, ".flac":45, ".ogg":8}

# ── Helpers ──────────────────────────────────────────────────────────────────
def now_ts():
    now = datetime.datetime.now(datetime.timezone.utc)
    return now.strftime('%Y-%m-%d %H:%M:%S.') + f'{now.microsecond//1000:03d} +00:00'

def make_id(s: str) -> str:
    return str(zlib.crc32(s.encode("utf-8")) & 0xFFFFFFFF)

def new_uuid() -> str:
    return str(uuid.uuid4())

def next_usn(con) -> int:
    """Return max(rb_local_usn) + 1 across all DJ tables."""
    m = 0
    for tbl in ("djmdPlaylist", "djmdContent", "djmdSongPlaylist", "djmdCue"):
        v = con.execute(f"SELECT MAX(rb_local_usn) FROM {tbl}").fetchone()[0]
        if v and v > m:
            m = v
    return m + 1

def open_db(path: Path):
    con = sqlite3.connect(str(path))
    con.execute(f"PRAGMA key='{KEY}'")
    con.execute("PRAGMA cipher='sqlcipher'")
    con.execute("PRAGMA legacy=4")
    con.execute("PRAGMA foreign_keys=OFF")
    return con

# ── Step 1 – backup ──────────────────────────────────────────────────────────
def backup(db_path: Path):
    stamp = datetime.date.today().strftime("%Y%m%d")
    dst   = db_path.with_suffix(f".db.backup_{stamp}")
    shutil.copy2(db_path, dst)
    print(f"  Backed up to {dst.name}")
    return dst

# ── Step 2 – remove old duplicate trees ──────────────────────────────────────
def get_all_descendants(con, root_ids):
    all_ids = list(str(i) for i in root_ids)
    queue   = list(all_ids)
    while queue:
        parent = queue.pop()
        children = [r[0] for r in con.execute(
            "SELECT ID FROM djmdPlaylist WHERE ParentID=?", (parent,)).fetchall()]
        for cid in children:
            scid = str(cid)
            all_ids.append(scid)
            queue.append(scid)
    return list(set(all_ids))

def remove_old_trees(con, dry_run):
    # Identify canonical folder IDs (the ones to keep)
    canonical_ids = set()
    for r in con.execute(
            "SELECT ID, Name FROM djmdPlaylist WHERE ParentID='root' AND Attribute=1"
    ).fetchall():
        if r[1] in CANONICAL_ROOT_FOLDERS:
            canonical_ids.add(str(r[0]))

    # Collect all root-level folder IDs that are NOT canonical and NOT protected
    to_remove_roots = []
    for r in con.execute(
            "SELECT ID, Name, Attribute FROM djmdPlaylist WHERE ParentID='root'"
    ).fetchall():
        pid, name, attr = str(r[0]), r[1], r[2]
        if pid in canonical_ids:
            continue
        if name in PROTECTED_ROOT_NAMES:
            continue
        if attr not in (0, 1):   # skip special types like -128
            continue
        to_remove_roots.append(pid)

    if not to_remove_roots:
        print("  No old trees to remove.")
        return

    to_delete = get_all_descendants(con, to_remove_roots)
    pl_count  = con.execute(
        f"SELECT COUNT(*) FROM djmdPlaylist WHERE ID IN ({','.join('?'*len(to_delete))})",
        to_delete).fetchone()[0]
    sp_count  = con.execute(
        f"SELECT COUNT(*) FROM djmdSongPlaylist WHERE PlaylistID IN ({','.join('?'*len(to_delete))})",
        to_delete).fetchone()[0]
    print(f"  Removing {pl_count} playlist rows + {sp_count} track-links …", end="")
    if not dry_run:
        ph = ",".join("?" * len(to_delete))
        con.execute(f"DELETE FROM djmdSongPlaylist WHERE PlaylistID IN ({ph})", to_delete)
        con.execute(f"DELETE FROM djmdPlaylist WHERE ID IN ({ph})", to_delete)
        con.commit()
    print(" done.")

# ── Step 3 – add missing playlists ───────────────────────────────────────────
def build_xml_tree(node, path=()):
    """Walk XML NODE tree and return {tuple_path: [track_keys]} for every playlist.
    Uses tuples instead of slash-joined strings so folder names containing '/'
    are treated as literals and never mis-parsed as path separators."""
    result = {}
    for child in node.findall("NODE"):
        name      = child.get("Name", "")
        full_path = path + (name,)
        if child.get("Type") == "1":
            result[full_path] = [t.get("Key") for t in child.findall("TRACK")]
        else:
            result.update(build_xml_tree(child, full_path))
    return result

def collect_db_pl_map(con, parent_id, prefix=()):
    """Walk DB playlist tree and return {tuple_path: playlist_id} for every playlist.
    Uses tuples so names containing '/' are never split incorrectly."""
    result = {}
    for r in con.execute(
            "SELECT ID, Name, Attribute FROM djmdPlaylist WHERE ParentID=?",
            (str(parent_id),)).fetchall():
        full = prefix + (r[1],)
        if r[2] == 0:
            result[full] = str(r[0])
        result.update(collect_db_pl_map(con, r[0], full))
    return result

def get_or_create_folder(con, path_parts, parent_id="root", usn=0):
    if not path_parts:
        return parent_id
    name     = path_parts[0]
    existing = con.execute(
        "SELECT ID FROM djmdPlaylist WHERE Name=? AND ParentID=? AND Attribute=1",
        (name, str(parent_id))).fetchone()
    if existing:
        folder_id = existing[0]
    else:
        folder_id = make_id(f"folder:{parent_id}:{name}")
        # Assign Seq = max sibling Seq + 1
        max_seq = con.execute(
            "SELECT COALESCE(MAX(Seq), -1) FROM djmdPlaylist WHERE ParentID=?",
            (str(parent_id),)).fetchone()[0]
        con.execute("""INSERT INTO djmdPlaylist
            (ID,Seq,Name,Attribute,ParentID,UUID,
             rb_data_status,rb_local_data_status,rb_local_deleted,rb_local_synced,
             rb_local_usn,created_at,updated_at)
            VALUES (?,?,?,1,?,?,0,0,0,0,?,?,?)""",
            (folder_id, max_seq + 1, name, str(parent_id), new_uuid(),
             usn, now_ts(), now_ts()))
    return get_or_create_folder(con, path_parts[1:], folder_id, usn)

def add_missing_playlists(con, xml_tree, xml_trackid_to_dbid, dry_run):
    # Build current DB path map
    db_pl_map = {}
    for r in con.execute(
            "SELECT ID, Name FROM djmdPlaylist WHERE ParentID='root' AND Attribute=1"
    ).fetchall():
        db_pl_map.update(collect_db_pl_map(con, r[0], (r[1],)))
    for r in con.execute(
            "SELECT ID, Name FROM djmdPlaylist WHERE ParentID='root' AND Attribute=0"
    ).fetchall():
        db_pl_map[(r[1],)] = str(r[0])

    added_pl = added_tracks = 0
    usn = next_usn(con)
    for pl_path, xml_ids in sorted(xml_tree.items()):
        if pl_path in db_pl_map:
            continue
        parts     = list(pl_path)          # tuple → list of name segments
        pl_name   = parts[-1]
        parent_id = get_or_create_folder(con, parts[:-1], usn=usn)
        pl_id     = make_id(f"playlist:{parent_id}:{pl_name}")
        if con.execute("SELECT 1 FROM djmdPlaylist WHERE ID=?", (pl_id,)).fetchone():
            pl_id = make_id(f"playlist:{parent_id}:{pl_name}:v2")

        # Assign Seq = max sibling Seq + 1
        max_seq = con.execute(
            "SELECT COALESCE(MAX(Seq), -1) FROM djmdPlaylist WHERE ParentID=?",
            (str(parent_id),)).fetchone()[0]

        if not dry_run:
            con.execute("""INSERT INTO djmdPlaylist
                (ID,Seq,Name,Attribute,ParentID,UUID,
                 rb_data_status,rb_local_data_status,rb_local_deleted,rb_local_synced,
                 rb_local_usn,created_at,updated_at)
                VALUES (?,?,?,0,?,?,0,0,0,0,?,?,?)""",
                (pl_id, max_seq + 1, pl_name, str(parent_id), new_uuid(),
                 usn, now_ts(), now_ts()))
            for seq, xml_id in enumerate(xml_ids, 1):
                db_cid = xml_trackid_to_dbid.get(xml_id)
                if db_cid:
                    sp_id = make_id(f"sp:{pl_id}:{seq}:{xml_id}")
                    con.execute("""INSERT OR IGNORE INTO djmdSongPlaylist
                        (ID,PlaylistID,ContentID,TrackNo,UUID,
                         rb_data_status,rb_local_data_status,rb_local_deleted,rb_local_synced,
                         rb_local_usn,created_at,updated_at)
                        VALUES (?,?,?,?,?,0,0,0,0,?,?,?)""",
                        (sp_id, pl_id, db_cid, seq, new_uuid(),
                         usn, now_ts(), now_ts()))
                    added_tracks += 1
        added_pl += 1
        print(f"    + '{pl_name}' ({len(xml_ids)} tracks)")

    if not dry_run:
        con.commit()
    print(f"  Added {added_pl} playlists, {added_tracks} track-links.")

# ── Step 4 – add missing tracks ──────────────────────────────────────────────
def tonality_to_key_id(ton, key_map):
    if not ton:
        return 0
    camelot = ton[:-1] + ("M" if ton.upper().endswith("A") else "D")
    return key_map.get(camelot.upper(), 0)

def num_to_cue_kind(num):
    if num < 0: return 0
    if num < 3: return num + 1
    return num + 2   # skip Kind=4 (loop)

def add_missing_tracks(con, xml_collection, xml_tree, dry_run):
    db_paths = set(r[0] for r in con.execute("SELECT FolderPath FROM djmdContent").fetchall())
    key_map  = {r[1].upper(): r[0] for r in con.execute("SELECT ID, ScaleName FROM djmdKey").fetchall()}

    # Artist cache
    artist_cache = {r[0]: r[1] for r in con.execute("SELECT Name, ID FROM djmdArtist").fetchall()}
    def get_or_create_artist(name):
        if not name: return None
        if name in artist_cache: return artist_cache[name]
        aid = make_id(f"artist:{name}")
        if con.execute("SELECT 1 FROM djmdArtist WHERE ID=? AND Name!=?", (aid, name)).fetchone():
            aid = make_id(f"artist:{name}:v2")
        if not con.execute("SELECT 1 FROM djmdArtist WHERE ID=?", (aid,)).fetchone():
            con.execute("""INSERT INTO djmdArtist
                (ID,Name,UUID,rb_data_status,rb_local_data_status,
                 rb_local_deleted,rb_local_synced,created_at,updated_at)
                VALUES (?,?,?,0,0,0,0,?,?)""",
                (aid, name, new_uuid(), now_ts(), now_ts()))
        artist_cache[name] = aid
        return aid

    inserted_ids   = {}   # decoded_path → content_id
    xml_id_to_path = {}   # xml TrackID  → decoded_path

    missing = []
    for t in xml_collection:
        path = unquote(t.get("Location", "").replace("file://localhost", ""))
        xml_id_to_path[t.get("TrackID")] = path
        if ("Factory Sounds" in path or "Traktor Pro 3" in path):
            continue
        if path not in db_paths:
            missing.append((path, t))

    print(f"  {len(missing)} tracks to insert …")
    usn = next_usn(con)
    for path, t in missing:
        title      = t.get("Name", "")
        artist     = t.get("Artist", "")
        bpm        = round(float(t.get("AverageBpm", "0") or "0") * 100)
        length     = int(float(t.get("TotalTime", "0") or "0"))
        bitrate    = int(t.get("BitRate", "0") or "0")
        samplerate = int(t.get("SampleRate", "44100") or "44100")
        comment    = t.get("Comments", "")
        key_id     = tonality_to_key_id(t.get("Tonality", ""), key_map) or None
        ftype      = FILE_TYPE.get(Path(path).suffix.lower(), 1)
        filename   = Path(path).name

        content_id  = make_id(f"track:{path}")
        if con.execute("SELECT 1 FROM djmdContent WHERE ID=?", (content_id,)).fetchone():
            content_id = make_id(f"track:{path}:v2")

        track_uuid = new_uuid()
        artist_id  = get_or_create_artist(artist)

        if not dry_run:
            con.execute("""INSERT INTO djmdContent (
                ID,FolderPath,FileNameL,Title,ArtistID,BPM,Length,
                FileType,BitRate,SampleRate,Commnt,Rating,ColorID,KeyID,
                UUID,rb_data_status,rb_local_data_status,rb_local_deleted,rb_local_synced,
                rb_local_usn,created_at,updated_at)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,0,0,?,?,257,0,0,0,?,?,?)""",
                (content_id, path, filename, title, artist_id,
                 bpm, length, ftype, bitrate, samplerate, comment,
                 key_id, track_uuid, usn, now_ts(), now_ts()))

            for cm in t.findall("POSITION_MARK"):
                if int(cm.get("Type", "0")) == 4:
                    continue
                num    = int(cm.get("Num", "-1"))
                inmsc  = round(float(cm.get("Start", "0")) * 1000)
                end    = float(cm.get("End", "-0.001"))
                outmsc = round(end * 1000) if end > 0 else -1
                kind   = num_to_cue_kind(num)
                color  = -1 if kind > 0 else 3
                cue_id = make_id(f"cue:{content_id}:{kind}:{inmsc}")
                con.execute("""INSERT OR IGNORE INTO djmdCue (
                    ID,ContentID,InMsec,InFrame,InMpegFrame,InMpegAbs,
                    OutMsec,OutFrame,OutMpegFrame,OutMpegAbs,
                    Kind,Color,ColorTableIndex,ActiveLoop,Comment,
                    BeatLoopSize,CueMicrosec,ContentUUID,UUID,
                    rb_data_status,rb_local_data_status,rb_local_deleted,rb_local_synced,
                    rb_local_usn,created_at,updated_at)
                    VALUES (?,?,?,0,0,0,?,0,0,0,?,?,−1,0,?,0,0,?,?,0,0,0,0,?,?,?)""",
                    (cue_id, content_id, inmsc, outmsc, kind, color,
                     cm.get("Name","") or "", track_uuid, new_uuid(),
                     usn, now_ts(), now_ts()))

        inserted_ids[path] = content_id

    if not dry_run:
        con.commit()

    # Map xml TrackID → db content ID (both new and existing)
    all_db = {r[0]: r[1] for r in con.execute("SELECT FolderPath, ID FROM djmdContent").fetchall()}
    xml_trackid_to_dbid = {}
    for xml_id, path in xml_id_to_path.items():
        dbid = all_db.get(path)
        if dbid:
            xml_trackid_to_dbid[xml_id] = dbid

    # Link newly inserted tracks into their playlists (uses tuple paths — no slash ambiguity)
    links_added = 0
    if not dry_run:
        db_pl_map = {}
        for r in con.execute(
                "SELECT ID, Name FROM djmdPlaylist WHERE ParentID='root' AND Attribute=1"
        ).fetchall():
            db_pl_map.update(collect_db_pl_map(con, r[0], (r[1],)))
        for r in con.execute(
                "SELECT ID, Name FROM djmdPlaylist WHERE ParentID='root' AND Attribute=0"
        ).fetchall():
            db_pl_map[(r[1],)] = str(r[0])

        def link_playlists(node, path=()):
            nonlocal links_added
            for child in node.findall("NODE"):
                name = child.get("Name", "")
                full = path + (name,)
                if child.get("Type") == "1":
                    db_pl_id = db_pl_map.get(full)
                    if db_pl_id:
                        existing = set(r[0] for r in con.execute(
                            "SELECT ContentID FROM djmdSongPlaylist WHERE PlaylistID=?",
                            (db_pl_id,)).fetchall())
                        seq = con.execute(
                            "SELECT COALESCE(MAX(TrackNo),0) FROM djmdSongPlaylist WHERE PlaylistID=?",
                            (db_pl_id,)).fetchone()[0]
                        for i, tn in enumerate(child.findall("TRACK")):
                            db_cid = xml_trackid_to_dbid.get(tn.get("Key"))
                            if db_cid and db_cid not in existing:
                                sp_id = make_id(f"sp_link:{db_pl_id}:{db_cid}")
                                con.execute("""INSERT OR IGNORE INTO djmdSongPlaylist
                                    (ID,PlaylistID,ContentID,TrackNo,UUID,rb_data_status,
                                     rb_local_data_status,rb_local_deleted,rb_local_synced,
                                     rb_local_usn,created_at,updated_at)
                                    VALUES (?,?,?,?,?,0,0,0,0,?,?,?)""",
                                    (sp_id, db_pl_id, db_cid, seq+i+1, new_uuid(),
                                     usn, now_ts(), now_ts()))
                                links_added += 1
                else:
                    link_playlists(child, full)

        link_playlists(xml_root := ET.parse(  # noqa: reuse already-parsed root below
            str(Path.home() / "projects/rekordbox-tools/traktor_to_rekordbox.xml")
        ).getroot().find("PLAYLISTS").find("NODE"))
        con.commit()

    print(f"  Inserted {len(inserted_ids)} tracks, {links_added} playlist links.")
    return xml_trackid_to_dbid

# ── Main ─────────────────────────────────────────────────────────────────────
def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--xml",      default=str(XML_PATH), help="Path to Rekordbox XML")
    ap.add_argument("--dry-run",  action="store_true",   help="Preview changes without writing")
    args = ap.parse_args()

    xml_path = Path(args.xml)
    if not xml_path.exists():
        raise SystemExit(f"XML not found: {xml_path}")
    if not DB_PATH.exists():
        raise SystemExit(f"master.db not found: {DB_PATH}")

    print(f"{'[DRY RUN] ' if args.dry_run else ''}Rekordbox DB cleanup/sync")
    print(f"  XML:  {xml_path}")
    print(f"  DB:   {DB_PATH}\n")

    # Parse XML once
    tree = ET.parse(str(xml_path))
    root = tree.getroot()
    xml_collection  = root.find("COLLECTION").findall("TRACK")
    xml_tree        = build_xml_tree(root.find("PLAYLISTS").find("NODE"))

    print("1. Backing up …")
    if not args.dry_run:
        backup(DB_PATH)

    con = open_db(DB_PATH)

    print("\n2. Removing old/duplicate folder trees …")
    remove_old_trees(con, args.dry_run)

    print("\n3. Adding missing playlists …")
    # Build xml_trackid → db_content_id map for existing tracks
    db_path_map        = {r[0]: r[1] for r in con.execute("SELECT FolderPath, ID FROM djmdContent").fetchall()}
    xml_trackid_to_dbid = {}
    for t in xml_collection:
        p = unquote(t.get("Location","").replace("file://localhost",""))
        if p in db_path_map:
            xml_trackid_to_dbid[t.get("TrackID")] = db_path_map[p]

    add_missing_playlists(con, xml_tree, xml_trackid_to_dbid, args.dry_run)

    print("\n4. Adding missing tracks …")
    xml_trackid_to_dbid = add_missing_tracks(con, xml_collection, xml_tree, args.dry_run)

    # Final stats
    if not args.dry_run:
        tracks = con.execute("SELECT COUNT(*) FROM djmdContent").fetchone()[0]
        pls    = con.execute("SELECT COUNT(*) FROM djmdPlaylist WHERE Attribute=0").fetchone()[0]
        cues   = con.execute("SELECT COUNT(*) FROM djmdCue").fetchone()[0]
        sp     = con.execute("SELECT COUNT(*) FROM djmdSongPlaylist").fetchone()[0]
        print(f"\n✓ Done.  {tracks} tracks · {cues} cues · {pls} playlists · {sp} links")

    con.close()

if __name__ == "__main__":
    main()
